### ISSUE TITLE
Define premium offer

### ISSUE THREAD

**Issue by defusioner** [defusioner/ShopList-Tracker#1]
## Premium features
- [x] Number of items per subscription (Premium: 1000, Free: 30) - **I want a big list to cover my shopping needs** #45 
- [x] Create, update, delete new lists (Premium: 10, Free: 1) - **I want to go out with friends, we create a list and we use it for our shopping** #39 #42 #43
- [x] Simultaneous sessions from different devices (Premium: 5, Free: 1) - **I want to log in and do not relog from another device** #44
